# Trusty Beta requires sudo per https://docs.travis-ci.com/user/ci-environment/
sudo: required
dist: trusty

services:
  - docker

# We don't actually use anything java, but this feels the least jarring "language"
language: java

# Even though this shouldn't be needed, one build failed because of SSH known hosts:
# https://travis-ci.org/openzipkin/docker-zipkin/builds/78704161
addons:
  ssh_known_hosts: github.com

# Version tags are used to trigger these Travis CI runs
branches:
  only:
    - /^[0-9]+\.[0-9]+\.[0-9]+$/

# jq is used in release.sh to parse the responses of the quay.io API
install:
  - sudo wget https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64 -O /usr/local/bin/jq
  - sudo chmod o+x /usr/local/bin/jq

before_script:
  # Log in to Docker Hub, needed to mirror images built on quay.io
  - docker login -u dockerzipkindeployer -p "$DOCKERHUB_PASSWORD"

script:
 # Also known as doit.sh
 - ./release.sh $TRAVIS_TAG

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/ead3c37d57527214e9f2
      - https://webhooks.gitter.im/e/e57478303f87ecd7bffc
    on_success: change
    on_failure: always

env:
  global:
    # The release process syncs minor and major version tags to the newly built subminor version tag
    # via the quay.io API, using these credentials.
    - secure: "v9DuzsUNqYPGdRVd5c4sTckKwtbTpcJ5CqviifUw+jbBWmbUHKoXsACn43fh5w9BEUMQ1SsFl88Idw7r+HTffeTeDoTDEjaVRZK0Ud5HRi1WwSAnnSsy2OlyJqPKVqTF8OEjqquIL+K3cXhVKr+rKsrlsjFA/58uzS7OyM+VG1oWfFK5WSUkoDpfn42zWhnshBvSv42GkSdXzvARWyQovkgS8kJVl2HicXk3Jhw4M2I+rQDrgOYywxmQQUKKXGMRqjxe+S38qLuOYWBU5Me+U+OqepYnXCXct3UAAe33ZYaxTqyFlcerKls4hzS6aJ1HFIQtu0OlDc2smY2C8b6G0lhUVWLe6Lg4EZ9czvPLM+AMC4HsgKWCBARXDjXqVNao1EMgqHP84C1SgXUYlmlfor7RrfiUf/5h1HMqe6/OEHoskbhA7W8R0iDi5XyOpLSKrLIflA+A03QHyuvFMmCV8dl6GbybQ6X153zmLuQip7nnZZCmtKnEQ0mbubpOG5DIcnPPBjf4AVUL7lsvBvfQ5Wa09kXFBltRQE21/l3UQS9zhBDqrBoU87J9g2/8srBWUXzFppMVRv2QsNN7UiCA9w+YWGQSDT/kiJOMFSx8GrotYHayFNwpB7+MBotMKsUzFswYuepwTRF2VQly4uSFbbq2YWlVzg+bw2hYvfUUN6E="
    # The release process pushes images to Docker Hub, using these credentials
    - secure: "XgeUk0zBMKkm1dFl5JiHkMWBMXdr7PWsDGRfmhsyhj6mOlgBAFs2ve1fIyqY1YboyOy4hO/ljr+zchCgMt3OW9GMeCmmMip0bV5Xot4LrmkQX/LWes8LKiDqlikISM9pAdPmzVYqJxt/KhfglBZFMBTfNrTmJhtbLBgSocvp/HDbG1INiDoeCzaEw5H6zwAIZK2vz1T6fAgQ3kyDg0Zv5lNP7ylPXO0T5qwF/7wzq6dZmkwONQHyHLm/3kaD/AI2KCclqWf7GBaitfkb03N40ZcehGo28BVTgfnOgM9GYtPKRwb6spD08R1JNwsXCZqa3SAiJKN5iOXp9BLAymlAHRkRtkHLkjspmm9AtX72RqPQ7dRGVqMzH9xIIukUNAdvukho8sie/fM2JU6oncGhsC4W47Pxx93cqpUXknbWCDxvS2XiYxo+cYHbfsTWn5pgrmcG6mXHICF5JHFML3lqN7LTXXIkG3g/oJhhmo9DgJZ5yDq0Iyfpsd5NWbvfsme1Q/gppkmNbJOHd13oodt2iBKl7t69YkYaHHTvJa8houm6e4wGjN5S1PTj6eRAYK4mc4xxl3lYpZPPaP6aQHVVfJTBd6ka6tIXFxPHG2nQu5F/b/IgnuOqkAFh21CjCtWLqSJ4HmK3kXVllhYS6qqNCBPfZuStymuqJRD6qYKdfr0="
